dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: HSqDzk1WTU4C0qqJI9mzbVVPLhxNrzHieksnAgKJBD6dmgdwDOZ7WbN9v5L1/2UjtktKpfve4hznmWMzKt+wzELsxW1HZiMdaP3ATEPQLz7goS+kB3tC3vUnQG6L37S9g1rmkkTp2sJz1Exk9I2u7k93SAWasswpT6kZlcztU9rgYFnT+Wok5FrZsiQag/QbB2uVY1pBHWSdJKkgWMDXpGv6WHP+3C1RBhUxHlPytadVkYHFt4XlpET8PHKfoMlMm136j3gV+mvfVAe4smhV4SpKOquy1r55YJtJYvSBVOykHzxDR0zjmKb2oNvSgwytWTrrn2rdFIumOM6HfyndpFUBZPHjLzlJhQ50tCSwBRrs6oLppOG5+rc42NXTZ4iS6cCsKQ4w/qFju3y7nGNtUYixxtKiJMTpnsRDxuE3iER3DawR7Pjx/WtR04KIerQF/4SNwsV8Urxa/m/bg3UDEbeHEXTcObr0AkkxN/+3lj1SeKvCCyP6PEyQYtBAWXghiX3ZRwIz6+XC8cXH4n9ZllkIoJI8X4g3BCBxum9nxtRTUgp9V2YapSnWklz8Ipvf399/69yYtP5jB2nEyn+/o6IKDQckD7yqnjniuRrQuKlOqxswewFjHTYFM+spMlbtUuzoGAzNWHgAREFZUIamqtYDOs4i97MrwjeMGrvseEo=
  - secure: Bl5pPOn5fXNNXwSLcXw8IcMJqRZS7nwPcfH0hZnZWyd5B6IS/z3Qxl/JrzsDYY6FF5xcSjdse3V49srnQTS/SaP+K0giFIeecZZ3TYvc1odDsOryqkuNauTrK8hBc5o7LBg2I+E9+gXbxIIPZ6KBZcPVVuJsKxUgxfEj39UXnDRhW4baBlYDnZcqCg+qWVTAL8eCFO4KWayn7WpHhP5ko3LRSqq6AsqXKfxVu7CKCfOrlwY7t8dNdYaFAw0lrPUAqLEwYbLfVn9mB+vOK4KxQeYkFu0V4zG6HwjOvUqo554N90ESICRubW14/riAAuPYfXon9XQFXeXgf6aBBn5aXs76snkIWYMzinHBtDr/Q+pqBbWlwUkrfHintQMp7uhi8Zcgh7DcNnWe9KL6cqTZg3Ky4P/GVOC6C/BGv5ZljS983aY4XUNlLnJ0s1Ih8q3FAnMYnntoK1JkR0pf3l/PWsnQQxgjAdXaIKi+IcVtfJdtUG/ggk49TXaPqFY5jEEQqPg/rQOkgX+JUayvykdUA3zURDbIrkxX/Ui8RTNMzdPWz+yOokuS28ZWZLsqK2B+RSTaKKQJ50vVeED23i9nXEUEJIk3IA9G+H1cnzdzXcBCXAZUKK/8cVssiiYSAYoXcs1CZk5Q+EKK/aaCxFBqSKjTxSOcrmX/bgnWv3U7L+Q=
  - secure: X3TCyqvQaG+81amPxKKVGWjdgBKEvpF8YPJrX1Li6zrG6H17bjCFl6xDw2hUFms5tSgImbhZ0ATnLEaWqVEkMNPt92nURatZBuabZg9IHubYX0HvMWgFIBYpZq46hPowgAM99oOp0ArgzbWFb8IQPtPgsZ4lRS2hMr0phcUOjurAkaR5IDiMuWluG/WA8OJskT22orSJr3vcDZbMp4cUnjugBbPe6iVSUyTEW96aOqBia9qVmfXB3+7mhoVGmIzbJqnjk3jRol/zwsEPRPbdiIJQxRpB/zteqY4ojAgBJZK+LApMij4AuHxsvcSHqdnQuPFIyrDCwMcx85DNKa5qSb8mpBWbsZ7UmWtMj0/9zANC5VwYz41CJKO1IQdDAHYa7VbRUF6HzkIb6LmtPkdkjAwn9j7Hq7I6R7QGFoKfQ1hdCbYzp227zurDeqto8aPdzCqnKoWKza9RbwAMA87VlnQtzQ/lGeuu+zj13fiOEQGrcWsdsIuncw5Znjdy30mMqnDlWlcXvfMRjt6kAYC1uM655PkQiNApYGfpoUdbil5KAiSV/VaBBEn4z1FGMrKQl9VJaRdUtL0B3Z1JkBRkPQN1ZxeP2CYO9l4GL5wF35X7F49LzflTa2o8v5Cpzjzox6opyj+J+68dp7dSebvE+x0N61xwO5wrAEJBGLf19yw=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
